#!/bin/bash

RELNAME="$1"

if [ "$RELNAME" == "asmack" ]; then
  echo "Building for aSmack"
  cp build.gradle.asmack build.gradle
else
  echo "Building for Smack"
  cp build.gradle.smack build.gradle
fi
